os:
  - linux
language: python
python:
  - 3.6
install: 
  - pip install codecov
script:
  - python setup.py install
  - pytest -v
  - py.test  tests/ --cov-report term --cov="."
after_success:
  - codecov
