os:
  - linux
language: python
python:
  - 3.6
install: 
  - pip install codecov
script:
  - python setup.py install
  - py.test --cov-report term --cov=tests/
env:
  - CODECOV_TOKEN="6a521bf9-f74e-48af-871f-bd47a7176d60"
after_success:
  - codecov
