os:
  - linux
language: python
python:
  - 3.6
install: 
  - pip install coverage
script:
  - python setup.py install
  - pytest -v
  - coverage run tests
after_success:
  - bash <(curl -s https://codecov.io/bash)
