os:
  - linux
language: python
python:
  - 3.6
install: 
  - pip install codecov
  - pip install pytest-cov
script:
  - python setup.py install
  - pytest --cov-report term-missing --cov=robin tests/
env:
  - CODECOV_TOKEN="6a521bf9-f74e-48af-871f-bd47a7176d60"
after_success:
  - codecov
